export const NAMES = {
  NAME: "name",
  EMAIL: "email",
  PASSWORD: "password",
  PRICE: "price",
  STOCK: "stock",
  QUANTITY: "quantity",
  ORDER_DATE: "orderDate",
  TRANSFER_DATE: "transferDate",
  SALE_DATE: "saleDate",
  START_DATE: "startDate",
  COMPLETED_DATE: "date",
  TO_USER: "toUser",
  CUSTOMER_NAME: "customerName",
  DATE: "date",
  DATE_FROM: "dateFrom",
  DATE_TO: "endDate",
  TOTAL: "total",
  PREVIEW: "preview",
} as const;

export const LABELS = {
  NAME: "Name",
  EMAIL: "Email",
  PASSWORD: "Password",

  CATEGORY_NAME: "Category Name",
  PRODUCT_NAME: "Product Name",
  P_NAME: "P.Name",
  PRODUCT_PRICE: "Product Price",
  PRODUCT_STOCK: "Product Stock",
  ORDER_DATE: "Order Date",
  PRICE: "Price",
  STOCK: "Stock",
  REMAINING_STOCK: "Remaining Stock",
  QUANTITY: "Quantity",
  CATEGORY: "Category",
  COMPANY: "Company",
  COMPANIES: "Companies",
  USER_NAME: "User Name",
  SCREEN_LIST: "Screen List",
  DATE: "Date",
  FROM_COMPANY: "From Company",
  TO_COMPANY: "To Company",
  PRODUCT: "Product",
  PRODUCTS: "Products",
  TO_USER: "Customer",
  FROM: "From",
  PHONE_NUMBER: "Phone Number",
  TO: "To",
  OPENING_STOCK: "Opening Stock",
  O_STOCK: "O.Stock",
  PRODUCTION_STOCK: "Production",
  PROD_STOCK: "Prod.",
  INWARD: "Inward",
  IN: "In",
  OUTWARD: "Outward",
  OUT: "Out",
  BALANCE_STOCK: "Balance Stock",
  B_STOCK: "B.Stock",
  COMPANY_NAME: "Company Name",
  C_NAME: "C.Name",

  APPR_DATE: "Apx. Complete Date",
  COMPLETED_DATE: "Complete Date",

  PENDING: "Pending",
  COMPLETED: "Completed",
  STATUS: "Status",
  PRODUCTION_REPORT: "Production Report",
  SALE_REGISTER: "Sale Register",
  TRANSFER_REGISTER: "Transfer Register",
  TRANSFER_TYPE: "Transfer Type",
  REPORT_TYPE: "Report Type",
  ORDER_TYPE: "Order Type",
} as const;

export const PLACEHOLDERS = {
  NAME: "Enter Name",
  EMAIL: "Enter Email",
  PASSWORD: "Enter Password",
  PHONE_NUMBER: "Enter Phone Number",

  SEARCH: "Search.....",
  CATEGORY_NAME: "Enter Category Name",
  PRODUCT_NAME: "Enter Product Name",
  PRICE: "Enter Price",
  STOCK: "Enter Stock",
  QUANTITY: "Enter Quantity",
  CATEGORY: "Select Category",
  COMPANY: "Select Company",
  USER_NAME: "Enter User Name",
  DATE: "Select Date",
  FROM_COMPANY: "Select Company",
  TO_COMPANY: "Select Company",
  PRODUCT: "Select Product",
  TO_USER: "Enter Customer",
  FROM: "Select From",
  TO: "Select To",

  APPR_DATE: "Select Apx. Complete Date",
  COMPLETED_DATE: "Select Complete Date",
  STATUS: "Select Status",
  REPORT_TYPE: "Select Report Type",
  ORDER_TYPE: "Select Order Type",
} as const;
